In [2]:
import numpy as np

In [5]:
lst =[1,2,3]

- Criar um array(vector) apartir de uma lista

In [4]:
np.array(lst)

array([1, 2, 3])

- Criar uma matriz apartir de uma lista de listas

In [6]:
m_lst =[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(m_lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- O numero de colchetes indica o numero de dimeções, duas no caso

### metodos importantes de np

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

- matriz de zeros

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

- matriz identidade

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- np.linspace(), parecido com o arange 

In [19]:
np.linspace(0, 10,2)

array([ 0., 10.])

In [20]:
np.linspace(0, 10,3)

array([ 0.,  5., 10.])

- np.random.rand(), valores aleatoris dentro de um escopo de 0-1
- distribuição uniforme

In [22]:
np.random.rand(5)

array([0.13387919, 0.318539  , 0.9289127 , 0.28236081, 0.36955271])

In [23]:
np.random.rand(4)*100

array([83.96038073, 39.99312375, 42.04693478, 52.1725956 ])

In [24]:
np.random.rand(3,2)

array([[0.75619735, 0.63243145],
       [0.02642828, 0.83430085],
       [0.50875267, 0.43382912]])

In [25]:
np.random.rand(3,2,2)

array([[[0.08569371, 0.41303319],
        [0.90033638, 0.9581808 ]],

       [[0.7563427 , 0.74696409],
        [0.0340254 , 0.94904791]],

       [[0.30297521, 0.03011541],
        [0.77928813, 0.15268253]]])

- np.random.randn(), retirado da distribuição normal;
- distribuição normal (**distribuição gaussiana**) é uma das distribuições de probabilidade mais utilizadas para modelar fenômenos naturais.
- méida zero, dp 1

In [27]:
np.random.randn(4)

array([-0.71740469, -0.00411279, -0.86767473,  2.0768021 ])

- np.random.randint(), gera numeros inteiros de dentro do intervalo determinado

In [28]:
np.random.randint(0,100,10)

array([69, 73, 77, 86, 91, 80, 80, 43, 12, 90])

- reshape, altera a forma do array

In [32]:
arr = np.random.rand(15)

In [33]:
arr

array([0.90947538, 0.72558792, 0.14187338, 0.1985678 , 0.22367482,
       0.84673818, 0.05967328, 0.70868506, 0.57474958, 0.95727446,
       0.22369217, 0.06630929, 0.48239937, 0.29276174, 0.60775583])

In [35]:
arr.reshape(5,3)

array([[0.90947538, 0.72558792, 0.14187338],
       [0.1985678 , 0.22367482, 0.84673818],
       [0.05967328, 0.70868506, 0.57474958],
       [0.95727446, 0.22369217, 0.06630929],
       [0.48239937, 0.29276174, 0.60775583]])

- atributo shape

In [36]:
arr.shape

(15,)

In [37]:
arr = arr.reshape(5,3)

In [38]:
arr.shape

(5, 3)

In [39]:
arr.max()

0.9572744575805393

In [40]:
arr.min()

0.059673281929995214

In [41]:
arr.argmax()

9

In [42]:
arr.argmin()

6

In [43]:
arr

array([[0.90947538, 0.72558792, 0.14187338],
       [0.1985678 , 0.22367482, 0.84673818],
       [0.05967328, 0.70868506, 0.57474958],
       [0.95727446, 0.22369217, 0.06630929],
       [0.48239937, 0.29276174, 0.60775583]])